### ISSUE TITLE
ReferenceError: performance is not defined

### ISSUE THREAD

**Issue by yuezhilanyi** [CesiumGS/3d-tiles-tools#108]
i haved installed 3d-tiles-tools in docker using two method, all ended with ReferenceError: performance is not defined
1. npm install 3d-tiles-tools
2. Developer Setup

can someone tell me, how to fix the error?

See error log below

> root@f3fb5877e994:/usr/src/3d-tiles-tools# npx ts-node ./src/cli/main.ts gzip -i ./specs/data/TilesetOfTilesets/ -o ./output/TilesetOfTilesets-gzipped/
[02:27:35.164] ERROR (CLI): performance is not defined
    err: {
      "type": "ReferenceError",
      "message": "performance is not defined",
      "stack":
          ReferenceError: performance is not defined
              at run (/usr/src/3d-tiles-tools/src/cli/main.ts:378:20)
              at runChecked (/usr/src/3d-tiles-tools/src/cli/main.ts:471:11)
              at Object.<anonymous> (/usr/src/3d-tiles-tools/src/cli/main.ts:477:1)
              at Module._compile (internal/modules/cjs/loader.js:1114:14)
              at Module.m._compile (/usr/src/3d-tiles-tools/node_modules/ts-node/src/index.ts:1618:23)
              at Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
              at Object.require.extensions.<computed> [as .ts] (/usr/src/3d-tiles-tools/node_modules/ts-node/src/index.ts:1621:12)
              at Module.load (internal/modules/cjs/loader.js:979:32)
              at Function.Module._load (internal/modules/cjs/loader.js:819:12)
              at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
              at phase4 (/usr/src/3d-tiles-tools/node_modules/ts-node/src/bin.ts:649:14)
              at bootstrap (/usr/src/3d-tiles-tools/node_modules/ts-node/src/bin.ts:95:10)
              at main (/usr/src/3d-tiles-tools/node_modules/ts-node/src/bin.ts:55:10)
              at Object.<anonymous> (/usr/src/3d-tiles-tools/node_modules/ts-node/src/bin.ts:800:3)
              at Module._compile (internal/modules/cjs/loader.js:1114:14)
              at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    }

see the dockerfile below 

> FROM node:14
>
> WORKDIR /usr/src/app
>
> RUN npm install 3d-tiles-tools

**Comment by yuezhilanyi** [comment]
using latest node fix the error

**Comment by javagl** [comment]
The package JSON currently states Node >= 16 as the version requirement. I'm still a bit surprised why it shouldn't find the `performance` class in Node 14 (maybe it required something special like `import ... from ... perf-hooks` or so...?), but in any case, the tools would likely not run properly on Node 14 for other reasons, so there's probably no reason to investigate this further.

**Comment by yuezhilanyi** [comment]
Thank you very much for your reply. I did not find any information about the node version in the readme.md, so I suggest updating this information there.
