### ISSUE TITLE
i have error about combine command.

### ISSUE THREAD

**Issue by JHP0124** [CesiumGS/3d-tiles-tools#137]
![2024-06-13 11 50 36](https://github.com/CesiumGS/3d-tiles-tools/assets/105851614/188f67bb-f240-44f5-b391-85febaf504e2)

![image](https://github.com/CesiumGS/3d-tiles-tools/assets/105851614/52646d72-9e1c-47ae-9893-7906fc6dea6d)

![image](https://github.com/CesiumGS/3d-tiles-tools/assets/105851614/09e89114-1989-4e8e-9f8c-bad70c566565)

this is example structure picture .

and i attached json file and please check json file
[tileset.json](https://github.com/user-attachments/files/15813140/tileset.json)
[Tile_+000_+021.json](https://github.com/user-attachments/files/15813145/Tile_%2B000_%2B021.json)

so i tried to combine this dataset.

but... 3d-tiles-tools show me this error.

![image](https://github.com/CesiumGS/3d-tiles-tools/assets/105851614/66b2bcab-77d3-4aad-908c-ec8ed9ea6f3e)

:~/light$ npx 3d-tiles-tools combine -i ./ -o ./combine_test
Need to install the following packages:
3d-tiles-tools@0.4.2
Ok to proceed? (y) y

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
[11:47:51.808] ERROR (CLI): No data found for Tile_+001_+021/Tile_+001_+021/Tile_+001_+021_L20_0uuuu20.b3dm
    err: {
      "type": "TilesetError",
      "message": "No data found for Tile_+001_+021/Tile_+001_+021/Tile_+001_+021_L20_0uuuu20.b3dm",
      "stack":
          Error: No data found for Tile_+001_+021/Tile_+001_+021/Tile_+001_+021_L20_0uuuu20.b3dm
              at TilesetCombiner.combineContentInternal (/home/anjion/.npm/_npx/e97e2e75cde22e22/node_modules/3d-tiles-tools/build/src/tools/tilesetProcessing/TilesetCombiner.js:168:19)
              at TilesetCombiner.combineTileInternal (/home/anjion/.npm/_npx/e97e2e75cde22e22/node_modules/3d-tiles-tools/build/src/tools/tilesetProcessing/TilesetCombiner.js:132:24)
              at /home/anjion/.npm/_npx/e97e2e75cde22e22/node_modules/3d-tiles-tools/build/src/tools/tilesetProcessing/TilesetCombiner.js:116:24
              at Tiles.traverseExplicitInternal (/home/anjion/.npm/_npx/e97e2e75cde22e22/node_modules/3d-tiles-tools/build/src/tilesets/tilesets/Tiles.js:111:37)
              at Tiles.traverseExplicitInternal (/home/anjion/.npm/_npx/e97e2e75cde22e22/node_modules/3d-tiles-tools/build/src/tilesets/tilesets/Tiles.js:114:29)
              at async Tiles.traverseExplicitInternal (/home/anjion/.npm/_npx/e97e2e75cde22e22/node_modules/3d-tiles-tools/build/src/tilesets/tilesets/Tiles.js:114:17)
              at async Tiles.traverseExplicit (/home/anjion/.npm/_npx/e97e2e75cde22e22/node_modules/3d-tiles-tools/build/src/tilesets/tilesets/Tiles.js:100:9)
              at async TilesetCombiner.combineTilesetsInternal (/home/anjion/.npm/_npx/e97e2e75cde22e22/node_modules/3d-tiles-tools/build/src/tools/tilesetProcessing/TilesetCombiner.js:114:9)
              at async TilesetCombiner.combineContentInternal (/home/anjion/.npm/_npx/e97e2e75cde22e22/node_modules/3d-tiles-tools/build/src/tools/tilesetProcessing/TilesetCombiner.js:191:13)
              at async TilesetCombiner.combineTileInternal (/home/anjion/.npm/_npx/e97e2e75cde22e22/node_modules/3d-tiles-tools/build/src/tools/tilesetProcessing/TilesetCombiner.js:132:13)
              at async /home/anjion/.npm/_npx/e97e2e75cde22e22/node_modules/3d-tiles-tools/build/src/tools/tilesetProcessing/TilesetCombiner.js:116:13
              at async Tiles.traverseExplicitInternal (/home/anjion/.npm/_npx/e97e2e75cde22e22/node_modules/3d-tiles-tools/build/src/tilesets/tilesets/Tiles.js:111:31)
              at async Tiles.traverseExplicitInternal (/home/anjion/.npm/_npx/e97e2e75cde22e22/node_modules/3d-tiles-toolanjion@LAPTOP-FEEB6E09:~/light$
              at async Tiles.traverseExplicit (/home/anjion/.npm/_npx/e97e2e75cde22e22/node_modules/3d-tiles-tools/build/src/tilesets/tilesets/Tiles.js:100:9)
              at async TilesetCombiner.combineTilesetsInternal (/home/anjion/.npm/_npx/e97e2e75cde22e22/node_modules/3d-tiles-tools/build/src/tools/tilesetProcessing/TilesetCombiner.js:114:9)
              at async TilesetCombiner.combineInternal (/home/anjion/.npm/_npx/e97e2e75cde22e22/node_modules/3d-tiles-tools/build/src/tools/tilesetProcessing/TilesetCombiner.js:85:9)
    }

i was never repeated the path. 
but combine command is repeated the path.
even other laptop too

i think something is wrong

someone have simillar experience? or someone have solution about this error?

**Comment by javagl** [comment]
This is currently discussed in a _very_ long-running internal support thread. It does not make sense to open a bunch of duplicate threads and issues like
- https://github.com/CesiumGS/cesium/issues/12024
- (the same issue:) https://community.cesium.com/t/i-have-problem-with-visittile-visitlfvisible-visitvisiblechildrenneartofar/32694
- _this_ issue
- (the same issue:) https://community.cesium.com/t/i-have-error-about-combine-command/33053
- ...
 
**in addition** to the ongoing support thread. While it can be useful to make parts of a discussion _public_, so that others can chime in, _nobody_ will be able to provide any help here or in these issues _without_ the relevant data, and right now, this is only scattering the discussion into multiple places. 

Just in case somebody wonders, here's the input data:
[isolated.zip](https://github.com/user-attachments/files/15817688/isolated.zip)
This data was extracted from the full data, in a desperate attempt to reprodue the issue, but it is apparently is not sufficient for reproducing the issue reliably.

Maybe there is something wrong with the `combine` command. If there is an issue with the `combine` command, then it should be described in a form so that others can _reproduce_ it, with test data. I assume that this will be figured out in the support thread. If it turns out that the `combine` command is not working as expected, I'll open a new, proper issue for that.
